(() => {
  'use strict';

  // ---------------------------------------------------------------------
  // Static data
  // ---------------------------------------------------------------------

  const ROLES = [
    { value: 'manager', en: 'Manager', zh: '經理' },
    { value: 'pm', en: 'Project Manager', zh: '專案經理' },
    { value: 'sales', en: 'Sales', zh: '業務' },
    { value: 'sw', en: 'SW Engineer', zh: '軟體工程師' },
    { value: 'hw', en: 'HW Engineer', zh: '硬體工程師' },
    { value: 'fpga', en: 'FPGA Engineer', zh: 'FPGA工程師' },
    { value: 'mech', en: 'Mechanical Engineer', zh: '機構工程師' },
    { value: 'qa', en: 'QA Engineer', zh: '品保工程師' },
    { value: 'marketing', en: 'Marketing', zh: '行銷' },
    { value: 'customer', en: 'Customer', zh: '客戶' },
    { value: 'other', en: 'Other', zh: '其他' },
  ];

  const roleLabel = (value, lang) => {
    const r = ROLES.find((x) => x.value === value);
    if (!r) return '';
    return lang === 'zh' ? r.zh : r.en;
  };

  const TEXT = {
    en: {
      docTitle: 'Meeting Minutes',
      dateLabel: 'Date',
      subjectLabel: 'Subject',
      attendeesTitle: 'Attendees',
      thRole: 'Role',
      thName: 'Name',
      contentTitle: 'Meeting Content',
      todoTitle: 'Action Items',
      thTask: 'Task',
      thOwner: 'Owner',
      thDue: 'Due Date',
      notesTitle: 'Additional Notes',
      noAttendees: 'No attendees recorded.',
      noContent: 'No content recorded.',
      noTodo: 'No action items.',
      noNotes: 'No additional notes.',
      noOwner: '—',
      noDue: '—',
      generatedBy: 'Generated by Meeting Minutes Generator',
    },
    zh: {
      docTitle: '會議記錄',
      dateLabel: '會議日期',
      subjectLabel: '會議主旨',
      attendeesTitle: '與會人員',
      thRole: '職務',
      thName: '姓名',
      contentTitle: '會議內容',
      todoTitle: '待辦事項',
      thTask: '事項',
      thOwner: '負責人',
      thDue: '期限',
      notesTitle: '其他補充項目',
      noAttendees: '尚未填寫與會人員。',
      noContent: '尚未填寫會議內容。',
      noTodo: '尚未填寫待辦事項。',
      noNotes: '無其他補充事項。',
      noOwner: '—',
      noDue: '—',
      generatedBy: '由會議記錄產生器產生',
    },
  };

  const STORAGE_KEY = 'meeting-minutes-draft-v1';

  // ---------------------------------------------------------------------
  // DOM refs
  // ---------------------------------------------------------------------

  const $ = (sel) => document.querySelector(sel);

  const dateInput = $('#meeting-date');
  const subjectInput = $('#meeting-subject');
  const notesInput = $('#notes');

  const attendeeList = $('#attendee-list');
  const contentList = $('#content-list');
  const todoList = $('#todo-list');

  const previewBox = $('#preview-box');
  const genStatus = $('#gen-status');
  const pdfRoot = $('#pdf-render-root');

  let rowIdCounter = 0;
  const nextId = () => `row-${++rowIdCounter}`;

  // ---------------------------------------------------------------------
  // Row builders
  // ---------------------------------------------------------------------

  function buildRoleOptions(select, selectedValue) {
    const placeholder = document.createElement('option');
    placeholder.value = '';
    placeholder.textContent = '選擇職務 / Select role';
    select.appendChild(placeholder);
    ROLES.forEach((r) => {
      const opt = document.createElement('option');
      opt.value = r.value;
      opt.textContent = `${r.en} ${r.zh}`;
      if (r.value === selectedValue) opt.selected = true;
      select.appendChild(opt);
    });
  }

  function addAttendeeRow(data = {}) {
    const id = nextId();
    const row = document.createElement('div');
    row.className = 'repeat-row attendee-row';
    row.dataset.id = id;

    const roleSelect = document.createElement('select');
    roleSelect.className = 'attendee-role';
    buildRoleOptions(roleSelect, data.role || '');

    const nameInput = document.createElement('input');
    nameInput.type = 'text';
    nameInput.className = 'attendee-name';
    nameInput.placeholder = '姓名 Name';
    nameInput.value = data.name || '';

    const removeBtn = document.createElement('button');
    removeBtn.type = 'button';
    removeBtn.className = 'row-remove';
    removeBtn.title = '移除 Remove';
    removeBtn.textContent = '✕';
    removeBtn.addEventListener('click', () => {
      row.remove();
      onChange();
    });

    row.appendChild(roleSelect);
    row.appendChild(nameInput);
    row.appendChild(removeBtn);
    attendeeList.appendChild(row);

    roleSelect.addEventListener('change', onChange);
    nameInput.addEventListener('input', onChange);
  }

  function addContentRow(value = '') {
    const id = nextId();
    const row = document.createElement('div');
    row.className = 'repeat-row content-row';
    row.dataset.id = id;

    const input = document.createElement('input');
    input.type = 'text';
    input.className = 'content-text';
    input.placeholder = '輸入討論重點 Discussion point';
    input.value = value;

    const removeBtn = document.createElement('button');
    removeBtn.type = 'button';
    removeBtn.className = 'row-remove';
    removeBtn.title = '移除 Remove';
    removeBtn.textContent = '✕';
    removeBtn.addEventListener('click', () => {
      row.remove();
      onChange();
    });

    row.appendChild(input);
    row.appendChild(removeBtn);
    contentList.appendChild(row);

    input.addEventListener('input', onChange);
  }

  function refreshTodoOwnerOptions() {
    const names = getAttendeeNames();
    document.querySelectorAll('.todo-owner').forEach((sel) => {
      const current = sel.value;
      sel.innerHTML = '';
      const noneOpt = document.createElement('option');
      noneOpt.value = '';
      noneOpt.textContent = '（未指定）Unassigned';
      sel.appendChild(noneOpt);
      names.forEach((n) => {
        const opt = document.createElement('option');
        opt.value = n;
        opt.textContent = n;
        if (n === current) opt.selected = true;
        sel.appendChild(opt);
      });
      if (names.includes(current)) sel.value = current;
    });
  }

  function getAttendeeNames() {
    return Array.from(document.querySelectorAll('.attendee-name'))
      .map((el) => el.value.trim())
      .filter(Boolean);
  }

  function addTodoRow(data = {}) {
    const id = nextId();
    const row = document.createElement('div');
    row.className = 'repeat-row todo-row';
    row.dataset.id = id;

    const taskInput = document.createElement('input');
    taskInput.type = 'text';
    taskInput.className = 'todo-task';
    taskInput.placeholder = '待辦事項內容 Task description';
    taskInput.value = data.task || '';

    const ownerSelect = document.createElement('select');
    ownerSelect.className = 'todo-owner';

    const dueInput = document.createElement('input');
    dueInput.type = 'date';
    dueInput.className = 'todo-due';
    if (data.due) dueInput.value = data.due;

    const removeBtn = document.createElement('button');
    removeBtn.type = 'button';
    removeBtn.className = 'row-remove';
    removeBtn.title = '移除 Remove';
    removeBtn.textContent = '✕';
    removeBtn.addEventListener('click', () => {
      row.remove();
      onChange();
    });

    row.appendChild(taskInput);
    row.appendChild(ownerSelect);
    row.appendChild(dueInput);
    row.appendChild(removeBtn);
    todoList.appendChild(row);

    refreshTodoOwnerOptions();
    if (data.owner) ownerSelect.value = data.owner;

    taskInput.addEventListener('input', onChange);
    ownerSelect.addEventListener('change', onChange);
    dueInput.addEventListener('change', onChange);
  }

  // ---------------------------------------------------------------------
  // Data collection
  // ---------------------------------------------------------------------

  function collectData() {
    const attendees = Array.from(attendeeList.querySelectorAll('.attendee-row')).map((row) => ({
      role: row.querySelector('.attendee-role').value,
      name: row.querySelector('.attendee-name').value.trim(),
    })).filter((a) => a.role || a.name);

    const content = Array.from(contentList.querySelectorAll('.content-text'))
      .map((el) => el.value.trim())
      .filter(Boolean);

    const todos = Array.from(todoList.children).map((row) => ({
      task: row.querySelector('.todo-task').value.trim(),
      owner: row.querySelector('.todo-owner').value,
      due: row.querySelector('.todo-due').value,
    })).filter((t) => t.task || t.owner || t.due);

    return {
      date: dateInput.value,
      subject: subjectInput.value.trim(),
      attendees,
      content,
      todos,
      notes: notesInput.value.trim(),
    };
  }

  // ---------------------------------------------------------------------
  // Formatting helpers
  // ---------------------------------------------------------------------

  function formatDate(isoDate, lang) {
    if (!isoDate) return lang === 'zh' ? '（未填寫日期）' : '(No date set)';
    const d = new Date(isoDate + 'T00:00:00');
    if (Number.isNaN(d.getTime())) return isoDate;
    const locale = lang === 'zh' ? 'zh-TW' : 'en-US';
    return new Intl.DateTimeFormat(locale, { year: 'numeric', month: 'long', day: 'numeric' }).format(d);
  }

  // ---------------------------------------------------------------------
  // Live preview (bilingual, based on raw data — always shown in mixed form)
  // ---------------------------------------------------------------------

  function renderPreview() {
    const data = collectData();
    const hasAny = data.date || data.subject || data.attendees.length || data.content.length || data.todos.length || data.notes;

    if (!hasAny) {
      previewBox.innerHTML = '<p class="preview-empty">開始填寫左側表單，這裡會即時顯示會議記錄內容。</p>';
      return;
    }

    const esc = (s) => (s || '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

    let html = '';
    html += `<p class="pv-title">${esc(data.subject) || '（未填寫主旨）'}</p>`;
    html += `<p>${esc(formatDate(data.date, 'zh'))}</p>`;

    html += '<h4>與會人員 Attendees</h4>';
    if (data.attendees.length) {
      html += data.attendees.map((a) => `<span class="pv-chip">${esc(roleLabel(a.role, 'zh'))}${a.name ? ' · ' + esc(a.name) : ''}</span>`).join('');
    } else {
      html += '<p class="preview-empty">尚未新增</p>';
    }

    html += '<h4>會議內容 Content</h4>';
    html += data.content.length
      ? '<ul>' + data.content.map((c) => `<li>${esc(c)}</li>`).join('') + '</ul>'
      : '<p class="preview-empty">尚未新增</p>';

    html += '<h4>待辦事項 Action Items</h4>';
    html += data.todos.length
      ? '<ul>' + data.todos.map((t) => `<li>${esc(t.task)}${t.owner ? ' — ' + esc(t.owner) : ''}${t.due ? ' (' + esc(t.due) + ')' : ''}</li>`).join('') + '</ul>'
      : '<p class="preview-empty">尚未新增</p>';

    html += '<h4>其他補充 Notes</h4>';
    html += data.notes ? `<p>${esc(data.notes)}</p>` : '<p class="preview-empty">無</p>';

    previewBox.innerHTML = html;
  }

  // ---------------------------------------------------------------------
  // PDF template rendering
  // ---------------------------------------------------------------------

  function buildPdfPage(data, lang) {
    const t = TEXT[lang];
    const page = document.createElement('div');
    page.className = `pdf-page lang-${lang}`;

    // Header
    const header = document.createElement('div');
    header.className = 'pdf-header';
    header.innerHTML = `
      <p class="pdf-doc-title">${t.docTitle}</p>
      <div class="pdf-doc-date">${t.dateLabel}<br>${formatDate(data.date, lang)}</div>
    `;
    page.appendChild(header);

    // Subject
    const subjectBox = document.createElement('div');
    subjectBox.className = 'pdf-subject-box';
    subjectBox.innerHTML = `
      <p class="pdf-label">${t.subjectLabel}</p>
      <p class="pdf-subject-text">${escapeHtml(data.subject) || '-'}</p>
    `;
    page.appendChild(subjectBox);

    // Attendees
    page.appendChild(buildSection(t.attendeesTitle, () => {
      if (!data.attendees.length) return emptyNote(t.noAttendees);
      const table = document.createElement('table');
      table.className = 'pdf-attendee-table';
      table.innerHTML = `
        <thead><tr><th style="width:40%">${t.thRole}</th><th>${t.thName}</th></tr></thead>
        <tbody>
          ${data.attendees.map((a) => `<tr><td>${escapeHtml(roleLabel(a.role, lang)) || '-'}</td><td>${escapeHtml(a.name) || '-'}</td></tr>`).join('')}
        </tbody>
      `;
      return table;
    }));

    // Content
    page.appendChild(buildSection(t.contentTitle, () => {
      if (!data.content.length) return emptyNote(t.noContent);
      const ul = document.createElement('ul');
      ul.className = 'pdf-bullet-list';
      ul.innerHTML = data.content.map((c) => `<li>${escapeHtml(c)}</li>`).join('');
      return ul;
    }));

    // Action items
    page.appendChild(buildSection(t.todoTitle, () => {
      if (!data.todos.length) return emptyNote(t.noTodo);
      const table = document.createElement('table');
      table.className = 'pdf-todo-table';
      table.innerHTML = `
        <thead><tr><th style="width:50%">${t.thTask}</th><th style="width:25%">${t.thOwner}</th><th style="width:25%">${t.thDue}</th></tr></thead>
        <tbody>
          ${data.todos.map((tItem) => `<tr><td>${escapeHtml(tItem.task) || '-'}</td><td>${escapeHtml(tItem.owner) || t.noOwner}</td><td>${tItem.due ? escapeHtml(formatDate(tItem.due, lang)) : t.noDue}</td></tr>`).join('')}
        </tbody>
      `;
      return table;
    }));

    // Notes
    page.appendChild(buildSection(t.notesTitle, () => {
      if (!data.notes) return emptyNote(t.noNotes);
      const p = document.createElement('p');
      p.className = 'pdf-notes-text';
      p.textContent = data.notes;
      return p;
    }));

    const footer = document.createElement('div');
    footer.className = 'pdf-footer';
    footer.textContent = `${t.generatedBy} · ${new Date().toISOString().slice(0, 10)}`;
    page.appendChild(footer);

    return page;
  }

  function buildSection(title, contentBuilder) {
    const section = document.createElement('div');
    section.className = 'pdf-section';
    const h = document.createElement('p');
    h.className = 'pdf-section-title';
    h.textContent = title;
    section.appendChild(h);
    section.appendChild(contentBuilder());
    return section;
  }

  function emptyNote(text) {
    const p = document.createElement('p');
    p.className = 'pdf-empty-note';
    p.textContent = text;
    return p;
  }

  function escapeHtml(s) {
    return (s || '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  }

  // ---------------------------------------------------------------------
  // PDF generation
  // ---------------------------------------------------------------------

  function setStatus(msg, kind) {
    genStatus.textContent = msg;
    genStatus.className = 'gen-status' + (kind ? ' ' + kind : '');
  }

  async function generatePdf(lang) {
    const data = collectData();

    if (!data.date || !data.subject) {
      setStatus(lang === 'zh' ? '請先填寫會議日期與會議主旨。' : 'Please fill in the meeting date and subject first.', 'error');
      return;
    }

    const buttons = [$('#btn-gen-en'), $('#btn-gen-zh')];
    buttons.forEach((b) => (b.disabled = true));
    setStatus(lang === 'zh' ? '正在產生 PDF，請稍候…' : 'Generating PDF, please wait…');

    try {
      pdfRoot.innerHTML = '';
      const page = buildPdfPage(data, lang);
      pdfRoot.appendChild(page);

      if (document.fonts && document.fonts.ready) {
        await document.fonts.ready;
      }

      const filenameDate = data.date || 'undated';
      const safeSubject = (data.subject || 'meeting').replace(/[^\w一-鿿-]+/g, '_').slice(0, 40);
      const suffix = lang === 'zh' ? 'ZH' : 'EN';
      const filename = `MeetingMinutes_${filenameDate}_${safeSubject}_${suffix}.pdf`;

      const opt = {
        margin: 0,
        filename,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true, backgroundColor: '#ffffff' },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: ['css', 'legacy'] },
      };

      await window.html2pdf().set(opt).from(page).save();
      setStatus(lang === 'zh' ? '✔ PDF 已產生並下載完成。' : '✔ PDF generated and downloaded.', 'success');
    } catch (err) {
      console.error(err);
      setStatus(lang === 'zh' ? '產生 PDF 時發生錯誤，請再試一次。' : 'Something went wrong generating the PDF. Please try again.', 'error');
    } finally {
      buttons.forEach((b) => (b.disabled = false));
      pdfRoot.innerHTML = '';
    }
  }

  // ---------------------------------------------------------------------
  // Persistence (localStorage draft)
  // ---------------------------------------------------------------------

  let saveTimer = null;
  function scheduleSave() {
    clearTimeout(saveTimer);
    saveTimer = setTimeout(saveDraft, 400);
  }

  function saveDraft() {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(collectData()));
    } catch (e) { /* ignore quota / privacy-mode errors */ }
  }

  function loadDraft() {
    let data;
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (!raw) return false;
      data = JSON.parse(raw);
    } catch (e) {
      return false;
    }
    if (!data) return false;

    dateInput.value = data.date || '';
    subjectInput.value = data.subject || '';
    notesInput.value = data.notes || '';

    (data.attendees || []).forEach((a) => addAttendeeRow(a));
    (data.content || []).forEach((c) => addContentRow(c));
    (data.todos || []).forEach((t) => addTodoRow(t));

    return true;
  }

  function clearForm() {
    if (!confirm('確定要清除所有已填寫的內容嗎？此動作無法復原。\nClear all entered data? This cannot be undone.')) return;
    dateInput.value = '';
    subjectInput.value = '';
    notesInput.value = '';
    attendeeList.innerHTML = '';
    contentList.innerHTML = '';
    todoList.innerHTML = '';
    try { localStorage.removeItem(STORAGE_KEY); } catch (e) { /* ignore */ }
    setStatus('');
    onChange();
  }

  // ---------------------------------------------------------------------
  // Wiring
  // ---------------------------------------------------------------------

  function onChange() {
    refreshTodoOwnerOptions();
    renderPreview();
    scheduleSave();
  }

  function init() {
    $('#btn-add-attendee').addEventListener('click', () => { addAttendeeRow(); onChange(); });
    $('#btn-add-content').addEventListener('click', () => { addContentRow(); onChange(); });
    $('#btn-add-todo').addEventListener('click', () => { addTodoRow(); onChange(); });
    $('#btn-clear').addEventListener('click', clearForm);
    $('#btn-gen-en').addEventListener('click', () => generatePdf('en'));
    $('#btn-gen-zh').addEventListener('click', () => generatePdf('zh'));

    [dateInput, subjectInput, notesInput].forEach((el) => el.addEventListener('input', onChange));

    const loaded = loadDraft();
    if (!loaded) {
      addAttendeeRow();
      addContentRow();
      addTodoRow();
    }
    onChange();
  }

  document.addEventListener('DOMContentLoaded', init);
})();
