(() => {
  'use strict';

  // ---------------------------------------------------------------------
  // Static data
  // ---------------------------------------------------------------------

  const ROLES = [
    { value: 'manager', en: 'Manager', zh: '經理' },
    { value: 'pm', en: 'Project Manager', zh: '專案經理' },
    { value: 'sales', en: 'Sales', zh: '業務' },
    { value: 'sales_manager', en: 'Sales Manager', zh: '業務經理' },
    { value: 'sw', en: 'SW Engineer', zh: '軟體工程師' },
    { value: 'hw', en: 'HW Engineer', zh: '硬體工程師' },
    { value: 'fpga', en: 'FPGA Engineer', zh: 'FPGA工程師' },
    { value: 'fae', en: 'FAE', zh: '現場應用工程師' },
    { value: 'avnet_dst', en: 'Avnet Design Service Team', zh: 'Avnet Design Service Team' },
    { value: 'customer', en: 'Customer', zh: '客戶' },
    { value: 'other', en: 'Other', zh: '其他' },
  ];

  const roleLabel = (value, lang) => {
    const r = ROLES.find((x) => x.value === value);
    if (!r) return '';
    return lang === 'zh' ? r.zh : r.en;
  };

  const TEXT = {
    en: {
      docTitle: 'Meeting Minutes',
      dateLabel: 'Date',
      subjectLabel: 'Subject',
      attendeesTitle: 'Attendees',
      thRole: 'Role',
      thName: 'Name',
      thCompany: 'Company',
      contentTitle: 'Meeting Content',
      todoTitle: 'Action Items',
      thTask: 'Task',
      thOwner: 'Owner',
      thDue: 'Due Date',
      notesTitle: 'Additional Notes',
      noAttendees: 'No attendees recorded.',
      noContent: 'No content recorded.',
      noTodo: 'No action items.',
      noNotes: 'No additional notes.',
      noOwner: '—',
      noDue: '—',
      generatedBy: 'Generated by Meeting Minutes Generator',
    },
    zh: {
      docTitle: '會議記錄',
      dateLabel: '會議日期',
      subjectLabel: '會議主旨',
      attendeesTitle: '與會人員',
      thRole: '職務',
      thName: '姓名',
      thCompany: '公司名稱',
      contentTitle: '會議內容',
      todoTitle: '待辦事項',
      thTask: '事項',
      thOwner: '負責人',
      thDue: '期限',
      notesTitle: '其他補充項目',
      noAttendees: '尚未填寫與會人員。',
      noContent: '尚未填寫會議內容。',
      noTodo: '尚未填寫待辦事項。',
      noNotes: '無其他補充事項。',
      noOwner: '—',
      noDue: '—',
      generatedBy: '由會議記錄產生器產生',
    },
  };

  const STORAGE_KEY = 'meeting-minutes-draft-v1';

  // ---------------------------------------------------------------------
  // DOM refs
  // ---------------------------------------------------------------------

  const $ = (sel) => document.querySelector(sel);

  const dateInput = $('#meeting-date');
  const subjectInput = $('#meeting-subject');
  const notesInput = $('#notes');

  const attendeeList = $('#attendee-list');
  const contentList = $('#content-list');
  const todoList = $('#todo-list');

  const previewBox = $('#preview-box');
  const genStatus = $('#gen-status');
  const pdfRoot = $('#pdf-render-root');
  const confirmOverlay = $('#confirm-overlay');
  const copyStatus = $('#copy-status');
  const outlookModalOverlay = $('#outlook-modal-overlay');
  const outlookCopyTarget = $('#outlook-copy-target');

  let rowIdCounter = 0;
  const nextId = () => `row-${++rowIdCounter}`;

  // ---------------------------------------------------------------------
  // Row builders
  // ---------------------------------------------------------------------

  function buildRoleOptions(select, selectedValue) {
    const placeholder = document.createElement('option');
    placeholder.value = '';
    placeholder.textContent = '選擇職務 / Select role';
    select.appendChild(placeholder);
    ROLES.forEach((r) => {
      const opt = document.createElement('option');
      opt.value = r.value;
      opt.textContent = r.en === r.zh ? r.en : `${r.en} ${r.zh}`;
      if (r.value === selectedValue) opt.selected = true;
      select.appendChild(opt);
    });
  }

  function addAttendeeRow(data = {}) {
    const id = nextId();
    const row = document.createElement('div');
    row.className = 'repeat-row attendee-row';
    row.dataset.id = id;

    const roleSelect = document.createElement('select');
    roleSelect.className = 'attendee-role';
    buildRoleOptions(roleSelect, data.role || '');

    const nameInput = document.createElement('input');
    nameInput.type = 'text';
    nameInput.className = 'attendee-name';
    nameInput.placeholder = '姓名 Name';
    nameInput.value = data.name || '';

    const companyInput = document.createElement('input');
    companyInput.type = 'text';
    companyInput.className = 'attendee-company';
    companyInput.placeholder = '公司名稱 Company (選填 optional)';
    companyInput.value = data.company || '';

    const removeBtn = document.createElement('button');
    removeBtn.type = 'button';
    removeBtn.className = 'row-remove';
    removeBtn.title = '移除 Remove';
    removeBtn.textContent = '✕';
    removeBtn.addEventListener('click', () => {
      row.remove();
      onChange();
    });

    row.appendChild(roleSelect);
    row.appendChild(nameInput);
    row.appendChild(companyInput);
    row.appendChild(removeBtn);
    attendeeList.appendChild(row);

    roleSelect.addEventListener('change', onChange);
    nameInput.addEventListener('input', onChange);
    companyInput.addEventListener('input', onChange);
  }

  function autoResizeTextarea(el) {
    el.style.height = 'auto';
    el.style.height = el.scrollHeight + 'px';
  }

  function addContentRow(value = '') {
    const id = nextId();
    const row = document.createElement('div');
    row.className = 'repeat-row content-row';
    row.dataset.id = id;

    const input = document.createElement('textarea');
    input.className = 'content-text';
    input.rows = 1;
    input.placeholder = '輸入討論重點，可換行 Discussion point (line breaks allowed)';
    input.value = value;

    const removeBtn = document.createElement('button');
    removeBtn.type = 'button';
    removeBtn.className = 'row-remove';
    removeBtn.title = '移除 Remove';
    removeBtn.textContent = '✕';
    removeBtn.addEventListener('click', () => {
      row.remove();
      onChange();
    });

    row.appendChild(input);
    row.appendChild(removeBtn);
    contentList.appendChild(row);

    input.addEventListener('input', () => {
      autoResizeTextarea(input);
      onChange();
    });
    requestAnimationFrame(() => autoResizeTextarea(input));
  }

  function refreshTodoOwnerOptions() {
    const names = getAttendeeNames();
    document.querySelectorAll('.todo-owner').forEach((sel) => {
      const current = sel.value;
      sel.innerHTML = '';
      const noneOpt = document.createElement('option');
      noneOpt.value = '';
      noneOpt.textContent = '（未指定）Unassigned';
      sel.appendChild(noneOpt);
      names.forEach((n) => {
        const opt = document.createElement('option');
        opt.value = n;
        opt.textContent = n;
        if (n === current) opt.selected = true;
        sel.appendChild(opt);
      });
      if (names.includes(current)) sel.value = current;
    });
  }

  function getAttendeeNames() {
    return Array.from(document.querySelectorAll('.attendee-name'))
      .map((el) => el.value.trim())
      .filter(Boolean);
  }

  function addTodoRow(data = {}) {
    const id = nextId();
    const row = document.createElement('div');
    row.className = 'repeat-row todo-row';
    row.dataset.id = id;

    const taskInput = document.createElement('input');
    taskInput.type = 'text';
    taskInput.className = 'todo-task';
    taskInput.placeholder = '待辦事項內容 Task description';
    taskInput.value = data.task || '';

    const ownerSelect = document.createElement('select');
    ownerSelect.className = 'todo-owner';

    const dueInput = document.createElement('input');
    dueInput.type = 'date';
    dueInput.className = 'todo-due';
    if (data.due) dueInput.value = data.due;

    const removeBtn = document.createElement('button');
    removeBtn.type = 'button';
    removeBtn.className = 'row-remove';
    removeBtn.title = '移除 Remove';
    removeBtn.textContent = '✕';
    removeBtn.addEventListener('click', () => {
      row.remove();
      onChange();
    });

    row.appendChild(taskInput);
    row.appendChild(ownerSelect);
    row.appendChild(dueInput);
    row.appendChild(removeBtn);
    todoList.appendChild(row);

    refreshTodoOwnerOptions();
    if (data.owner) ownerSelect.value = data.owner;

    taskInput.addEventListener('input', onChange);
    ownerSelect.addEventListener('change', onChange);
    dueInput.addEventListener('change', onChange);
  }

  // ---------------------------------------------------------------------
  // Data collection
  // ---------------------------------------------------------------------

  function collectData() {
    const attendees = Array.from(attendeeList.querySelectorAll('.attendee-row')).map((row) => ({
      role: row.querySelector('.attendee-role').value,
      name: row.querySelector('.attendee-name').value.trim(),
      company: row.querySelector('.attendee-company').value.trim(),
    })).filter((a) => a.role || a.name || a.company);

    const content = Array.from(contentList.querySelectorAll('.content-text'))
      .map((el) => el.value.trim())
      .filter(Boolean);

    const todos = Array.from(todoList.children).map((row) => ({
      task: row.querySelector('.todo-task').value.trim(),
      owner: row.querySelector('.todo-owner').value,
      due: row.querySelector('.todo-due').value,
    })).filter((t) => t.task || t.owner || t.due);

    return {
      date: dateInput.value,
      subject: subjectInput.value.trim(),
      attendees,
      content,
      todos,
      notes: notesInput.value.trim(),
    };
  }

  // ---------------------------------------------------------------------
  // Formatting helpers
  // ---------------------------------------------------------------------

  function formatDate(isoDate, lang) {
    if (!isoDate) return lang === 'zh' ? '（未填寫日期）' : '(No date set)';
    const d = new Date(isoDate + 'T00:00:00');
    if (Number.isNaN(d.getTime())) return isoDate;
    const locale = lang === 'zh' ? 'zh-TW' : 'en-US';
    return new Intl.DateTimeFormat(locale, { year: 'numeric', month: 'long', day: 'numeric' }).format(d);
  }

  // ---------------------------------------------------------------------
  // Live preview (bilingual, based on raw data — always shown in mixed form)
  // ---------------------------------------------------------------------

  function renderPreview() {
    const data = collectData();
    const hasAny = data.date || data.subject || data.attendees.length || data.content.length || data.todos.length || data.notes;

    if (!hasAny) {
      previewBox.innerHTML = '<p class="preview-empty">開始填寫左側表單，這裡會即時顯示會議記錄內容。</p>';
      return;
    }

    const esc = (s) => (s || '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

    let html = '';
    html += `<p class="pv-title">${esc(data.subject) || '（未填寫主旨）'}</p>`;
    html += `<p>${esc(formatDate(data.date, 'zh'))}</p>`;

    html += '<h4>與會人員 Attendees</h4>';
    if (data.attendees.length) {
      html += data.attendees.map((a) => `<span class="pv-chip">${esc(roleLabel(a.role, 'zh'))}${a.name ? ' · ' + esc(a.name) : ''}${a.company ? ' · ' + esc(a.company) : ''}</span>`).join('');
    } else {
      html += '<p class="preview-empty">尚未新增</p>';
    }

    html += '<h4>會議內容 Content</h4>';
    html += data.content.length
      ? '<ul>' + data.content.map((c) => `<li>${esc(c)}</li>`).join('') + '</ul>'
      : '<p class="preview-empty">尚未新增</p>';

    html += '<h4>待辦事項 Action Items</h4>';
    html += data.todos.length
      ? '<ul>' + data.todos.map((t) => `<li>${esc(t.task)}${t.owner ? ' — ' + esc(t.owner) : ''}${t.due ? ' (' + esc(t.due) + ')' : ''}</li>`).join('') + '</ul>'
      : '<p class="preview-empty">尚未新增</p>';

    html += '<h4>其他補充 Notes</h4>';
    html += data.notes ? `<p>${esc(data.notes)}</p>` : '<p class="preview-empty">無</p>';

    previewBox.innerHTML = html;
  }

  // ---------------------------------------------------------------------
  // PDF template rendering
  // ---------------------------------------------------------------------

  function buildPdfPage(data, lang) {
    const t = TEXT[lang];
    const page = document.createElement('div');
    page.className = `pdf-page lang-${lang}`;

    // Header
    const header = document.createElement('div');
    header.className = 'pdf-header';
    header.innerHTML = `
      <p class="pdf-doc-title">${t.docTitle}</p>
      <p class="pdf-doc-title-meta">${formatDate(data.date, lang)} · ${escapeHtml(data.subject) || '-'}</p>
    `;
    page.appendChild(header);

    // Date
    const dateBox = document.createElement('div');
    dateBox.className = 'pdf-subject-box';
    dateBox.innerHTML = `
      <p class="pdf-label">${t.dateLabel}</p>
      <p class="pdf-subject-text">${formatDate(data.date, lang)}</p>
    `;
    page.appendChild(dateBox);

    // Subject
    const subjectBox = document.createElement('div');
    subjectBox.className = 'pdf-subject-box';
    subjectBox.innerHTML = `
      <p class="pdf-label">${t.subjectLabel}</p>
      <p class="pdf-subject-text">${escapeHtml(data.subject) || '-'}</p>
    `;
    page.appendChild(subjectBox);

    // Attendees
    page.appendChild(buildSection(t.attendeesTitle, () => {
      if (!data.attendees.length) return emptyNote(t.noAttendees);
      const table = document.createElement('table');
      table.className = 'pdf-attendee-table';
      table.innerHTML = `
        <thead><tr><th style="width:35%">${t.thCompany}</th><th style="width:30%">${t.thRole}</th><th>${t.thName}</th></tr></thead>
        <tbody>
          ${data.attendees.map((a) => `<tr><td>${escapeHtml(a.company) || '-'}</td><td>${escapeHtml(roleLabel(a.role, lang)) || '-'}</td><td>${escapeHtml(a.name) || '-'}</td></tr>`).join('')}
        </tbody>
      `;
      return table;
    }));

    // Content
    page.appendChild(buildSection(t.contentTitle, () => {
      if (!data.content.length) return emptyNote(t.noContent);
      const ul = document.createElement('ul');
      ul.className = 'pdf-bullet-list';
      ul.innerHTML = data.content.map((c) => `<li>${escapeHtml(c)}</li>`).join('');
      return ul;
    }));

    // Action items
    page.appendChild(buildSection(t.todoTitle, () => {
      if (!data.todos.length) return emptyNote(t.noTodo);
      const table = document.createElement('table');
      table.className = 'pdf-todo-table';
      table.innerHTML = `
        <thead><tr><th style="width:50%">${t.thTask}</th><th style="width:25%">${t.thOwner}</th><th style="width:25%">${t.thDue}</th></tr></thead>
        <tbody>
          ${data.todos.map((tItem) => `<tr><td>${escapeHtml(tItem.task) || '-'}</td><td>${escapeHtml(tItem.owner) || t.noOwner}</td><td>${tItem.due ? escapeHtml(formatDate(tItem.due, lang)) : t.noDue}</td></tr>`).join('')}
        </tbody>
      `;
      return table;
    }));

    // Notes
    page.appendChild(buildSection(t.notesTitle, () => {
      if (!data.notes) return emptyNote(t.noNotes);
      const p = document.createElement('p');
      p.className = 'pdf-notes-text';
      p.textContent = data.notes;
      return p;
    }));

    const footer = document.createElement('div');
    footer.className = 'pdf-footer';
    footer.textContent = `${t.generatedBy} · ${new Date().toISOString().slice(0, 10)}`;
    page.appendChild(footer);

    return page;
  }

  function buildSection(title, contentBuilder) {
    const section = document.createElement('div');
    section.className = 'pdf-section';
    const h = document.createElement('p');
    h.className = 'pdf-section-title';
    h.textContent = title;
    section.appendChild(h);
    section.appendChild(contentBuilder());
    return section;
  }

  function emptyNote(text) {
    const p = document.createElement('p');
    p.className = 'pdf-empty-note';
    p.textContent = text;
    return p;
  }

  function escapeHtml(s) {
    return (s || '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  }

  function nl2br(s) {
    return escapeHtml(s).replace(/\n/g, '<br>');
  }

  // ---------------------------------------------------------------------
  // Outlook-compatible email HTML
  //
  // Outlook desktop renders HTML email with Word's engine, not a browser
  // engine: no CSS grid/flexbox, no external/`<style>`-block reliance
  // worth trusting, no web fonts. So this builds a table-based layout
  // with every style inline and a web-safe font stack — the same
  // approach used industry-wide for HTML email templates.
  // ---------------------------------------------------------------------

  const EMAIL_COLORS = {
    accent: '#2f5fe0',
    accentSoft: '#eef2fe',
    text: '#1c2333',
    muted: '#4a5266',
    border: '#e2e6f0',
    tableHeadBg: '#f7f9fc',
    faint: '#8a92a6',
    footer: '#9aa1b3',
  };

  function emailFontStack(lang) {
    return lang === 'zh'
      ? "'Microsoft JhengHei', 'PMingLiU', Calibri, Arial, sans-serif"
      : "Calibri, Arial, 'Microsoft JhengHei', sans-serif";
  }

  function buildEmailHtml(data, lang) {
    const t = TEXT[lang];
    const c = EMAIL_COLORS;
    const font = emailFontStack(lang);
    const dateStr = formatDate(data.date, lang);
    const subjectStr = escapeHtml(data.subject) || '-';

    const thStyle = `padding:8px 10px;border-bottom:1px solid ${c.border};font-size:11px;text-transform:uppercase;letter-spacing:0.3px;color:${c.muted};font-weight:bold;background:${c.tableHeadBg};font-family:${font};`;
    const tdStyle = `padding:8px 10px;border-bottom:1px solid ${c.border};font-size:13px;color:${c.text};font-family:${font};`;
    const emptyStyle = `padding:8px 10px;font-size:12px;color:${c.faint};font-style:italic;font-family:${font};`;

    const attendeeRows = data.attendees.length
      ? data.attendees.map((a) => `
        <tr>
          <td style="${tdStyle}">${escapeHtml(a.company) || '-'}</td>
          <td style="${tdStyle}">${escapeHtml(roleLabel(a.role, lang)) || '-'}</td>
          <td style="${tdStyle}">${escapeHtml(a.name) || '-'}</td>
        </tr>`).join('')
      : `<tr><td colspan="3" style="${emptyStyle}">${escapeHtml(t.noAttendees)}</td></tr>`;

    const contentBlock = data.content.length
      ? `<ul style="margin:0;padding-left:20px;font-family:${font};">${data.content.map((item) => `<li style="margin-bottom:6px;font-size:13px;color:${c.text};">${nl2br(item)}</li>`).join('')}</ul>`
      : `<p style="margin:0;font-size:12px;color:${c.faint};font-style:italic;font-family:${font};">${escapeHtml(t.noContent)}</p>`;

    const todoRows = data.todos.length
      ? data.todos.map((item) => `
        <tr>
          <td style="${tdStyle}">${escapeHtml(item.task) || '-'}</td>
          <td style="${tdStyle}">${escapeHtml(item.owner) || t.noOwner}</td>
          <td style="${tdStyle}">${item.due ? escapeHtml(formatDate(item.due, lang)) : t.noDue}</td>
        </tr>`).join('')
      : `<tr><td colspan="3" style="${emptyStyle}">${escapeHtml(t.noTodo)}</td></tr>`;

    const notesBlock = data.notes
      ? `<p style="margin:0;font-size:13px;color:${c.text};font-family:${font};">${nl2br(data.notes)}</p>`
      : `<p style="margin:0;font-size:12px;color:${c.faint};font-style:italic;font-family:${font};">${escapeHtml(t.noNotes)}</p>`;

    const sectionTitle = (label) => `<div style="font-size:12px;font-weight:bold;color:${c.accent};text-transform:uppercase;letter-spacing:0.4px;border-bottom:1px solid ${c.border};padding-bottom:6px;margin:0 0 10px;font-family:${font};">${escapeHtml(label)}</div>`;
    const infoBox = (label, value) => `
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:${c.accentSoft};margin-bottom:14px;">
        <tr><td style="padding:12px 16px;">
          <div style="font-size:11px;text-transform:uppercase;letter-spacing:0.3px;color:${c.muted};font-weight:bold;font-family:${font};">${escapeHtml(label)}</div>
          <div style="font-size:15px;font-weight:bold;color:${c.text};margin-top:3px;font-family:${font};">${value}</div>
        </td></tr>
      </table>`;

    return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f4f5fa;"><tr><td align="center" style="padding:20px 10px;">
<table role="presentation" width="640" cellpadding="0" cellspacing="0" border="0" style="width:640px;max-width:100%;background:#ffffff;border:1px solid ${c.border};font-family:${font};">
<tr><td style="padding:24px 28px 14px;border-bottom:3px solid ${c.accent};">
  <div style="font-size:22px;font-weight:bold;color:${c.text};font-family:${font};">${escapeHtml(t.docTitle)}</div>
  <div style="font-size:13px;color:${c.muted};font-weight:bold;margin-top:6px;font-family:${font};">${dateStr} &middot; ${subjectStr}</div>
</td></tr>
<tr><td style="padding:16px 28px 0;">
  ${infoBox(t.dateLabel, dateStr)}
  ${infoBox(t.subjectLabel, subjectStr)}
</td></tr>
<tr><td style="padding:2px 28px 0;">
  ${sectionTitle(t.attendeesTitle)}
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;margin-bottom:20px;">
    <tr><th style="${thStyle}" align="left">${escapeHtml(t.thCompany)}</th><th style="${thStyle}" align="left">${escapeHtml(t.thRole)}</th><th style="${thStyle}" align="left">${escapeHtml(t.thName)}</th></tr>
    ${attendeeRows}
  </table>
</td></tr>
<tr><td style="padding:0 28px 0;">
  ${sectionTitle(t.contentTitle)}
  <div style="margin-bottom:20px;">${contentBlock}</div>
</td></tr>
<tr><td style="padding:0 28px 0;">
  ${sectionTitle(t.todoTitle)}
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;margin-bottom:20px;">
    <tr><th style="${thStyle}" align="left">${escapeHtml(t.thTask)}</th><th style="${thStyle}" align="left">${escapeHtml(t.thOwner)}</th><th style="${thStyle}" align="left">${escapeHtml(t.thDue)}</th></tr>
    ${todoRows}
  </table>
</td></tr>
<tr><td style="padding:0 28px 0;">
  ${sectionTitle(t.notesTitle)}
  <div style="margin-bottom:20px;">${notesBlock}</div>
</td></tr>
<tr><td style="padding:12px 28px 24px;border-top:1px solid ${c.border};">
  <div style="font-size:10.5px;color:${c.footer};text-align:center;font-family:${font};">${escapeHtml(t.generatedBy)} &middot; ${new Date().toISOString().slice(0, 10)}</div>
</td></tr>
</table>
</td></tr></table>`;
  }

  function buildEmailPlainText(data, lang) {
    const t = TEXT[lang];
    const lines = [];
    lines.push(t.docTitle);
    lines.push(`${t.dateLabel}: ${formatDate(data.date, lang)}`);
    lines.push(`${t.subjectLabel}: ${data.subject || '-'}`);
    lines.push('');
    lines.push(t.attendeesTitle.toUpperCase());
    if (data.attendees.length) {
      data.attendees.forEach((a) => {
        lines.push(`- ${a.company || '-'} | ${roleLabel(a.role, lang) || '-'} | ${a.name || '-'}`);
      });
    } else {
      lines.push(t.noAttendees);
    }
    lines.push('');
    lines.push(t.contentTitle.toUpperCase());
    if (data.content.length) {
      data.content.forEach((item) => lines.push(`- ${item}`));
    } else {
      lines.push(t.noContent);
    }
    lines.push('');
    lines.push(t.todoTitle.toUpperCase());
    if (data.todos.length) {
      data.todos.forEach((item) => {
        const owner = item.owner || t.noOwner;
        const due = item.due ? formatDate(item.due, lang) : t.noDue;
        lines.push(`- ${item.task} (${t.thOwner}: ${owner}, ${t.thDue}: ${due})`);
      });
    } else {
      lines.push(t.noTodo);
    }
    lines.push('');
    lines.push(t.notesTitle.toUpperCase());
    lines.push(data.notes || t.noNotes);
    return lines.join('\n');
  }

  function setCopyStatus(msg, kind) {
    copyStatus.textContent = msg;
    copyStatus.className = 'gen-status' + (kind ? ' ' + kind : '');
  }

  function openOutlookModal(html) {
    outlookCopyTarget.innerHTML = html;
    outlookModalOverlay.hidden = false;

    const range = document.createRange();
    range.selectNodeContents(outlookCopyTarget);
    const selection = window.getSelection();
    selection.removeAllRanges();
    selection.addRange(range);
    outlookCopyTarget.focus();

    let autoCopied = false;
    try {
      autoCopied = document.execCommand('copy');
    } catch (e) {
      autoCopied = false;
    }

    const desc = $('#outlook-modal-desc');
    if (autoCopied) {
      desc.innerHTML = '✔ 內容已複製到剪貼簿，可直接貼到 Outlook 新郵件中。 <span class="en">Copied to your clipboard — paste it into a new Outlook email.</span>';
    } else {
      desc.innerHTML = '您的瀏覽器未允許自動複製，內容已為您反白選取，請按 <strong>Ctrl+C</strong>（Mac 請按 <strong>Cmd+C</strong>）複製，然後貼到 Outlook 新郵件中。 <span class="en">Please press Ctrl+C (Cmd+C on Mac) to copy the pre-selected content, then paste it into a new Outlook email.</span>';
    }
  }

  function closeOutlookModal() {
    outlookModalOverlay.hidden = true;
    outlookCopyTarget.innerHTML = '';
  }

  async function copyForOutlook(lang) {
    const data = collectData();
    if (!data.date || !data.subject) {
      setCopyStatus(lang === 'zh' ? '請先填寫會議日期與會議主旨。' : 'Please fill in the meeting date and subject first.', 'error');
      return;
    }

    const html = buildEmailHtml(data, lang);
    const text = buildEmailPlainText(data, lang);

    if (navigator.clipboard && window.ClipboardItem) {
      try {
        const item = new ClipboardItem({
          'text/html': new Blob([html], { type: 'text/html' }),
          'text/plain': new Blob([text], { type: 'text/plain' }),
        });
        await navigator.clipboard.write([item]);
        setCopyStatus(lang === 'zh' ? '✔ 已複製，請直接貼到 Outlook 新郵件中。' : '✔ Copied — paste it into a new Outlook email.', 'success');
        return;
      } catch (err) {
        // Fall through to the manual-copy modal below.
      }
    }

    setCopyStatus('');
    openOutlookModal(html);
  }

  // ---------------------------------------------------------------------
  // PDF generation
  // ---------------------------------------------------------------------

  function setStatus(msg, kind) {
    genStatus.textContent = msg;
    genStatus.className = 'gen-status' + (kind ? ' ' + kind : '');
  }

  // When this page runs inside the Claude Artifact viewer, script-triggered
  // downloads (the <a download> link html2pdf.js's own .save() creates) are
  // blocked by the sandbox. Use the platform's downloads capability instead
  // when it's available; otherwise fall back to a normal browser download.
  let downloadsCapabilityPromise = null;
  function getDownloadsCapability() {
    if (typeof window.claude === 'undefined' || typeof window.claude.use !== 'function') {
      return Promise.resolve(null);
    }
    if (!downloadsCapabilityPromise) {
      downloadsCapabilityPromise = window.claude.use('downloads').catch(() => null);
    }
    return downloadsCapabilityPromise;
  }

  function triggerBrowserDownload(blob, filename) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }

  async function generatePdf(lang) {
    const data = collectData();

    if (!data.date || !data.subject) {
      setStatus(lang === 'zh' ? '請先填寫會議日期與會議主旨。' : 'Please fill in the meeting date and subject first.', 'error');
      return;
    }

    const buttons = [$('#btn-gen-en'), $('#btn-gen-zh')];
    buttons.forEach((b) => (b.disabled = true));
    setStatus(lang === 'zh' ? '正在產生 PDF，請稍候…' : 'Generating PDF, please wait…');

    try {
      pdfRoot.innerHTML = '';
      const page = buildPdfPage(data, lang);
      pdfRoot.appendChild(page);

      if (document.fonts && document.fonts.ready) {
        await document.fonts.ready;
      }

      // Reset scroll before capture: html2canvas can miscompute the render
      // area (blank space + truncated content) if the page is scrolled.
      window.scrollTo(0, 0);

      const filenameDate = data.date || 'undated';
      const safeSubject = (data.subject || 'meeting').replace(/[^\w一-鿿-]+/g, '_').slice(0, 40);
      const suffix = lang === 'zh' ? 'ZH' : 'EN';
      const filename = `MeetingMinutes_${filenameDate}_${safeSubject}_${suffix}.pdf`;

      const opt = {
        margin: 0,
        filename,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true, backgroundColor: '#ffffff', scrollX: 0, scrollY: 0 },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: ['css', 'legacy'] },
      };

      const pdfBlob = await window.html2pdf().set(opt).from(page).outputPdf('blob');

      const downloadsApi = await getDownloadsCapability();
      if (downloadsApi) {
        try {
          await downloadsApi.save({ filename, data: pdfBlob });
          setStatus(lang === 'zh' ? '✔ PDF 已產生，請確認儲存。' : '✔ PDF generated — confirm the save prompt.', 'success');
        } catch (err) {
          if (err && err.code === 'declined') {
            setStatus(lang === 'zh' ? '已取消儲存。' : 'Save cancelled.', '');
          } else {
            throw err;
          }
        }
      } else {
        triggerBrowserDownload(pdfBlob, filename);
        setStatus(lang === 'zh' ? '✔ PDF 已產生並下載完成。' : '✔ PDF generated and downloaded.', 'success');
      }
    } catch (err) {
      console.error(err);
      setStatus(lang === 'zh' ? '產生 PDF 時發生錯誤，請再試一次。' : 'Something went wrong generating the PDF. Please try again.', 'error');
    } finally {
      buttons.forEach((b) => (b.disabled = false));
      pdfRoot.innerHTML = '';
    }
  }

  // ---------------------------------------------------------------------
  // Persistence (localStorage draft)
  // ---------------------------------------------------------------------

  let saveTimer = null;
  function scheduleSave() {
    clearTimeout(saveTimer);
    saveTimer = setTimeout(saveDraft, 400);
  }

  function saveDraft() {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(collectData()));
    } catch (e) { /* ignore quota / privacy-mode errors */ }
  }

  function loadDraft() {
    let data;
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (!raw) return false;
      data = JSON.parse(raw);
    } catch (e) {
      return false;
    }
    if (!data) return false;

    dateInput.value = data.date || '';
    subjectInput.value = data.subject || '';
    notesInput.value = data.notes || '';

    (data.attendees || []).forEach((a) => addAttendeeRow(a));
    (data.content || []).forEach((c) => addContentRow(c));
    (data.todos || []).forEach((t) => addTodoRow(t));

    return true;
  }

  function openClearConfirm() {
    confirmOverlay.hidden = false;
  }

  function closeClearConfirm() {
    confirmOverlay.hidden = true;
  }

  function clearForm() {
    closeClearConfirm();
    dateInput.value = '';
    subjectInput.value = '';
    notesInput.value = '';
    attendeeList.innerHTML = '';
    contentList.innerHTML = '';
    todoList.innerHTML = '';
    try { localStorage.removeItem(STORAGE_KEY); } catch (e) { /* ignore */ }
    setStatus('');
    onChange();
  }

  // ---------------------------------------------------------------------
  // Wiring
  // ---------------------------------------------------------------------

  function onChange() {
    refreshTodoOwnerOptions();
    renderPreview();
    scheduleSave();
  }

  function init() {
    $('#btn-add-attendee').addEventListener('click', () => { addAttendeeRow(); onChange(); });
    $('#btn-add-content').addEventListener('click', () => { addContentRow(); onChange(); });
    $('#btn-add-todo').addEventListener('click', () => { addTodoRow(); onChange(); });
    $('#btn-clear').addEventListener('click', openClearConfirm);
    $('#confirm-cancel').addEventListener('click', closeClearConfirm);
    $('#confirm-ok').addEventListener('click', clearForm);
    confirmOverlay.addEventListener('click', (e) => {
      if (e.target === confirmOverlay) closeClearConfirm();
    });
    document.addEventListener('keydown', (e) => {
      if (e.key === 'Escape' && !confirmOverlay.hidden) closeClearConfirm();
    });
    $('#btn-gen-en').addEventListener('click', () => generatePdf('en'));
    $('#btn-gen-zh').addEventListener('click', () => generatePdf('zh'));

    $('#btn-copy-en').addEventListener('click', () => copyForOutlook('en'));
    $('#btn-copy-zh').addEventListener('click', () => copyForOutlook('zh'));
    $('#outlook-modal-close').addEventListener('click', closeOutlookModal);
    outlookModalOverlay.addEventListener('click', (e) => {
      if (e.target === outlookModalOverlay) closeOutlookModal();
    });
    document.addEventListener('keydown', (e) => {
      if (e.key === 'Escape' && !outlookModalOverlay.hidden) closeOutlookModal();
    });

    [dateInput, subjectInput, notesInput].forEach((el) => el.addEventListener('input', onChange));

    const loaded = loadDraft();
    if (!loaded) {
      addAttendeeRow();
      addContentRow();
      addTodoRow();
    }
    onChange();
  }

  document.addEventListener('DOMContentLoaded', init);
})();
